name: Deploy to Production Environment

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: |
            cd /SIH/app
            git pull origin master
            pip install -r requirements.txt
            sudo systemctl restart utilities-api
