name: Deploy to Test Server

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Test Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.TEST_SERVER_SSH_KEY }}
          script: |
            cd /SIH/app
            git pull origin dev
            pip install -r requirements.txt
            sudo systemctl restart utilities-api
